gridmap:
  frequency: 1        # which frequency do we want to send an updated map?
  map_id: "map"      # map name
  size_x: 8           # size of x in meters
  size_y: 8           # size of y in meters
  resolution: 0.01    # size of each grid
  map_origin_x: 0     # center x position of the map
  map_origin_y: 0     # center y position of the map
  publish_topic: "/occupancy_grid" # The topic name of the map publisher 



obstacle_circle:
  create_static:
    use: true
    x: [-0.0]
    y: [-0.1]
    radius: [0.3]
  receiving_position:
    use: false
    topic: ["/gridmap_obstacle_1/pose", "/gridmap_obstacle_2/pose", "/gridmap_obstacle_3/pose"]
    radius: [0.36, 0.36, 0.36]
  receiving_position_gazebo:
    use: false
    topic: "/gazebo/model_states"
    radius: 0.5

visualization:
  static_circle_indices_to_visualize: [0]
  static_square_indices_to_visualize: []
  marker_color: [0.7, 0.7, 0.7, 1]
  marker_z: 1.8
