gridmap:
  frequency: 1        # which frequency do we want to send an updated map?
  map_id: "map"      # map name
  size_x: 50           # size of x in meters
  size_y: 50           # size of y in meters
  resolution: 0.01    # size of each grid
  map_origin_x: 0     # center x position of the map
  map_origin_y: 0     # center y position of the map
  publish_topic: "/costmap_node/costmap/costmap" # The topic name of the map publisher 



obstacles:
  create_static:
    use: true
    circles:
      x_center: [-0.5, -0.5, 1.8, 1.8]
      y_center: [-0.7, 1.9, -0.2, 2.4]
      radius: [0.5, 0.5, 0.5, 0.5]
    squares:
      x_center: [0, -6, -3.70, -2.3, 4.5]
      y_center: [0, 0, 0.82, 2.8, 1.5]
      length: [20, 5, 1.5, 2, 5]
      width: [10, 0.6, 0.6, 0.6, 0.6]
      orientation_deg: [0, 45, -45, -45, -45]
      line_thickness: [0.10, 0.1, 0.1, 0.1, 0.1]
  receiving_position:
    use: false
    circles:
      topics: []
      radius: []
    rectangles:
      topics: [/obstacles/rectangle2x1_1, /obstacles/rectangle2x1_2,/obstacles/rectangle2x1_3]
      lengths: [0.6, 0.6, 2.4]
      widths: [1.2, 1.2, 0.6]
      line_thickness: [0.05, 0.05, 0.05]
    lines:
      topics: [/obstacles/line1, /obstacles/line2, /obstacles/line3]
      lengths: [1.75, 1.75, 2.5]
      line_thickness: [0.1, 0.1, 0.1]

  receiving_position_gazebo:
    use: false
    topic: "/gazebo/model_states"
    radius: 0.5

visualization:
  static_circle_indices_to_visualize: [0, 1, 2, 3]
  static_square_indices_to_visualize: [1, 2, 3, 4, 5]
  marker_color: [0.7, 0.7, 0.7, 1]
  marker_z: 1.8
