gridmap:
  frequency: 1        # which frequency do we want to send an updated map?
  map_id: "map"      # map name
  size_x: 8           # size of x in meters
  size_y: 8           # size of y in meters
  resolution: 0.01    # size of each grid
  map_origin_x: 0     # center x position of the map
  map_origin_y: 0     # center y position of the map
  publish_topic: "/costmap_node/costmap/costmap" # The topic name of the map publisher 



obstacles:
  create_static:
    use: true
    circles:
      x_center: [0, 2]
      y_center: [-0.25, -0.75]
      radius: [0.5, 0.5]
    squares:
      x_center: [0]
      y_center: [0]
      length: [1]
      width: [2]
      orientation_deg: [45]
      line_thickness: [0.05]
  receiving_position:
    use: false
    circles:
      topics: []
      radius: []
    rectangles:
      topics: [/obstacle/square1]
      lengths: [1.2]
      widths: [0.6]
      line_thickness: [0.05]

  receiving_position_gazebo:
    use: false
    topic: "/gazebo/model_states"
    radius: 0.5
